---
- name: Install Nginx
  hosts: localhost
  become: true  # Run tasks with sudo/root privileges

  vars:
    nginx_package: nginx
    nginx_service: nginx
    nginx_config_file: /etc/nginx/nginx.conf
    nginx_default_site_config: /etc/nginx/sites-available/default
    nginx_port: 80

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: "{{ nginx_package }}"
        state: present

    - name: Ensure Nginx service is started and enabled
      service:
        name: "{{ nginx_service }}"
        state: started
        enabled: yes

    - name: Modify Nginx default site configuration
      template:
        src: nginx_default.conf.j2
        dest: "{{ nginx_default_site_config }}"
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: "{{ nginx_service }}"
        state: restarted
